version: '3.9'

services:
  postgres:
    container_name: rinha_postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: "200MB"

  rinha_api_01:
    container_name: rinha_api_1
    image: andarilhoz/rinha-de-backend-2024-q1-api:latest
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "25MB"
  
  rinha_api_02:
    container_name: rinha_api_2
    image: andarilhoz/rinha-de-backend-2024-q1-api:latest
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "25MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha_api_01
      - rinha_api_02
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "250MB"
  
networks:
  default:
    driver: bridge
    name: rinha-de-backend-2024-q1_default