version: '3.9'

services:
  postgres:
    container_name: rinha_postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: "200MB"

  rinha_api_01: &rinha_api_01
    image: andarilhoz/rinha-de-backend-2024-q1-api:latest
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: db
      DATABASE_USER: user
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password
      SERVER_PORT: 8080
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "25MB"
  
  rinha_api_02:
    <<: *rinha_api_01
    environment:
          DATABASE_HOST: postgres
          DATABASE_NAME: db
          DATABASE_USER: user
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: password
          SERVER_PORT: 8081
  nginx:
      image: nginx:1.25.3
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      restart: unless-stopped
      depends_on:
        - rinha_api_01
        - rinha_api_02
      ports:
        - "9999:9999"
      deploy:
        resources:
          limits:
            cpus: "0.15"
            memory: "50MB"