/**
 *
 *  TransacoesController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include <json/json.h>

#include "models/Transacoes.h"
#include "models/Saldos.h"
#include "models/Clientes.h"

#include "models/request/TransacaoRequest.h"

#include "filters/TransacoesValidator.h"

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r TransacoesController --resource=transacoes).
 * this class is a restful API controller.
 */
class TransacoesController: public drogon::HttpController<TransacoesController>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    ADD_METHOD_TO(TransacoesController::create,"clientes/{id}/transacoes", Post, "TransacoesValidator");
    //ADD_METHOD_TO(TransacoesController::update,"transacoes",Put,Options);
    METHOD_LIST_END

    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                int &&id,
                TransacaoRequest &&transacao);

    void updateSaldo(int id, int valor, 
                     const DbClientPtr &dbClientPtr);

    void addNewOperation(int id, TransacaoRequest transacao, 
                         const DbClientPtr &dbClientPtr);
    
    void checkIfUserExists(int id, const DbClientPtr &dbClientPtr, 
                           std::shared_ptr<drogon::AdviceCallback> callback);
};
