/**
 *
 *  UsersController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/orm/RestfulController.h>

#include "models/Transacoes.h"

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r UsersController --resource=transacoes).
 * this class is a restful API controller.
 */
class UsersController: public drogon::HttpController<UsersController>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    ADD_METHOD_TO(UsersController::getOne,"/clientes/{1}/extrato", Get);
    //ADD_METHOD_TO(UsersController::update,"transacoes",Put,Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
};
