/**
 *
 *  Saldos.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Saldos.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db;

const std::string Saldos::Cols::_id = "id";
const std::string Saldos::Cols::_cliente_id = "cliente_id";
const std::string Saldos::Cols::_valor = "valor";
const std::string Saldos::primaryKeyName = "id";
const bool Saldos::hasPrimaryKey = true;
const std::string Saldos::tableName = "saldos";

const std::vector<typename Saldos::MetaData> Saldos::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"cliente_id","int32_t","integer",4,0,0,1},
{"valor","int32_t","integer",4,0,0,1}
};
const std::string &Saldos::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Saldos::Saldos(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["cliente_id"].isNull())
        {
            clienteId_=std::make_shared<int32_t>(r["cliente_id"].as<int32_t>());
        }
        if(!r["valor"].isNull())
        {
            valor_=std::make_shared<int32_t>(r["valor"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            clienteId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            valor_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Saldos::Saldos(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clienteId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            valor_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

Saldos::Saldos(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("cliente_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["cliente_id"].isNull())
        {
            clienteId_=std::make_shared<int32_t>((int32_t)pJson["cliente_id"].asInt64());
        }
    }
    if(pJson.isMember("valor"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["valor"].isNull())
        {
            valor_=std::make_shared<int32_t>((int32_t)pJson["valor"].asInt64());
        }
    }
}

void Saldos::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clienteId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            valor_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void Saldos::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("cliente_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["cliente_id"].isNull())
        {
            clienteId_=std::make_shared<int32_t>((int32_t)pJson["cliente_id"].asInt64());
        }
    }
    if(pJson.isMember("valor"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["valor"].isNull())
        {
            valor_=std::make_shared<int32_t>((int32_t)pJson["valor"].asInt64());
        }
    }
}

const int32_t &Saldos::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Saldos::getId() const noexcept
{
    return id_;
}
void Saldos::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Saldos::PrimaryKeyType & Saldos::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Saldos::getValueOfClienteId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(clienteId_)
        return *clienteId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Saldos::getClienteId() const noexcept
{
    return clienteId_;
}
void Saldos::setClienteId(const int32_t &pClienteId) noexcept
{
    clienteId_ = std::make_shared<int32_t>(pClienteId);
    dirtyFlag_[1] = true;
}

const int32_t &Saldos::getValueOfValor() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(valor_)
        return *valor_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Saldos::getValor() const noexcept
{
    return valor_;
}
void Saldos::setValor(const int32_t &pValor) noexcept
{
    valor_ = std::make_shared<int32_t>(pValor);
    dirtyFlag_[2] = true;
}

void Saldos::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Saldos::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "cliente_id",
        "valor"
    };
    return inCols;
}

void Saldos::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClienteId())
        {
            binder << getValueOfClienteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getValor())
        {
            binder << getValueOfValor();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Saldos::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Saldos::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClienteId())
        {
            binder << getValueOfClienteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getValor())
        {
            binder << getValueOfValor();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Saldos::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClienteId())
    {
        ret["cliente_id"]=getValueOfClienteId();
    }
    else
    {
        ret["cliente_id"]=Json::Value();
    }
    if(getValor())
    {
        ret["valor"]=getValueOfValor();
    }
    else
    {
        ret["valor"]=Json::Value();
    }
    return ret;
}

Json::Value Saldos::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClienteId())
            {
                ret[pMasqueradingVector[1]]=getValueOfClienteId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getValor())
            {
                ret[pMasqueradingVector[2]]=getValueOfValor();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClienteId())
    {
        ret["cliente_id"]=getValueOfClienteId();
    }
    else
    {
        ret["cliente_id"]=Json::Value();
    }
    if(getValor())
    {
        ret["valor"]=getValueOfValor();
    }
    else
    {
        ret["valor"]=Json::Value();
    }
    return ret;
}

bool Saldos::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("cliente_id"))
    {
        if(!validJsonOfField(1, "cliente_id", pJson["cliente_id"], err, true))
            return false;
    }
    else
    {
        err="The cliente_id column cannot be null";
        return false;
    }
    if(pJson.isMember("valor"))
    {
        if(!validJsonOfField(2, "valor", pJson["valor"], err, true))
            return false;
    }
    else
    {
        err="The valor column cannot be null";
        return false;
    }
    return true;
}
bool Saldos::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Saldos::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("cliente_id"))
    {
        if(!validJsonOfField(1, "cliente_id", pJson["cliente_id"], err, false))
            return false;
    }
    if(pJson.isMember("valor"))
    {
        if(!validJsonOfField(2, "valor", pJson["valor"], err, false))
            return false;
    }
    return true;
}
bool Saldos::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Saldos::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
